### ISSUE TITLE
did all the steps, got this error

### ISSUE THREAD

**Issue by Yell038** [Square789/PydayNightFunkin#47]
Traceback (most recent call last):
  File "C:\Users\exampleuser\funnystuff\PydayNightFunkin\run.py", line 38, in <module>
    main()
  File "C:\Users\exampleuser\funnystuff\PydayNightFunkin\run.py", line 34, in main
    Game(2 - result.less_debug).run()
  File "C:\Users\exampleuser\funnystuff\PydayNightFunkin\pyday_night_funkin\main_game.py", line 176, in __init__
    cygl.initialize(gl)
  File "pyday_night_funkin\core\graphics\cygl\gl.pyx", line 126, in pyday_night_funkin.core.graphics.cygl.gl.initialize
    f(<size_t>ctypes.addressof(getattr(module, name)))
TypeError: invalid type

**Comment by Square789** [comment]
Thanks for reporting!
This error hints at a required OpenGL function missing, and that uncovered a pretty embarassing oversight: I haven't been specifying the needed OpenGL version to pyglet for the past two years. Just been getting a default 3.3 profile with all the required functions in it through sheer luck with extensions.
Run `git pull` and try again, c2617084b2098ba6a682b65412d36b89d5798bc9 hopefully fixes it.
If it doesn't, please post the output of `python -m pyglet.info` and maybe try updating your GPU drivers. If your GPU is older than around 10 years it is unlikely to support 4.5, sadly.

**Comment by Square789** [comment]
Yeah oops, there was more to it than that, i am not a good developer.
654d6f70cb56446cfce5a9fa86ec25e82968b2ce probably is closer to fixing it, i would really love to hear if it does or doesn't work out for you!

**Comment by Yell038** [comment]
i don't think i'm doing this right, but i pasted the code from the commits (too much of an idiot to learn how git pull works) and i got hit with the same error. and intel hd graphics 510 runs opengl 4.6 so i'm not sure what i'm doing wrong lol

**Comment by Yell038** [comment]
alright jyst installed pyglet and this is what i got after running python -m pyglet.info
[bruh.txt](https://github.com/Square789/PydayNightFunkin/files/11091404/bruh.txt)

**Comment by Square789** [comment]
I'm not seeing anything that should fail in there. Remember that since the extension source has changed you'll need to recompile the extensions via the `setup.py build_ext -i` command.
Follow the steps in [the README](https://github.com/Square789/PydayNightFunkin/blob/dade1854c9d8c19e1e90db6d29105d86722197ca/README.md#how-to-run) from 2. or 3., it should by all means work.  
Your local repo may be wrong since you manually copypasted commits in; if nothing else works, maybe try deleting the entire directory and redownloading the project.  
And thanks for sticking around here, considering the project's puny scope when compared to the mainstream engines it means a lot.
